### ISSUE TITLE
Faq

### ISSUE THREAD

**Issue by aj07** [ssbc/grants-process#4]
Is the grant process still open. I want to apply. Please, guide me.

**Comment by christianbundy** [comment]
I believe the last one was `%oK+RULTpgWoAe6QUH88oQ5CM8p7Fpeu3QAlr9w5ElKU=.sha256`, you can read more in the #ssbc-grants channel on SSB.

**Comment by aj07** [comment]
@christianbundy Link isn't working.

**Comment by christianbundy** [comment]
Sorry about that, you can follow `@eANNuLfzX/9rlGODXHYV8WJb+zw2h+d7YsT4vpYPvD0=.ed25519` for that message. By the way, as far as I can see the last grant was back in August.

**Comment by aj07** [comment]
@christianbundy Sorry, but none of the url is working there. Will you please share the excat url. Also, I checked all the pages and found last update was on July. IS there any chat channel where I can discuss?

**Comment by christianbundy** [comment]
These aren't URLs, they're addresses on the SSB network. You'll need something like [Patchwork](https://github.com/ssbc/patchwork/) to open them. I think there may be a #scuttlebutt IRC channel on freenode as well, but most of these grant discussions happen on SSB.

**Comment by aj07** [comment]
@christianbundy I have posted as @ETYwutMYloctKAHz8/PO+WKtRiOjGUlqxJQ8iLdcHH0=.ed25519

**Comment by prastut** [comment]
Hi @christianbundy if the grants are over can I make a PR updating the grants page with the information that grants have been closed for now?

**Comment by christianbundy** [comment]
@prastut A PR would be great, thanks!
